name: Publish

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build, Test and Publish
    timeout-minutes: 15
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUSLISH_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
